name: jsoniser
description: Dart package that provides class serialization to json.
version: 0.0.1
homepage: https://github.com/okaryo/jsoniser
repository: https://github.com/okaryo/jsoniser

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.17.12
